model: swin
# dataset: imagenettewoof
# dataset: synthetic
dataset: imagenet
attribution_methods:
  - GradCAMPlusPlus
  - LayerCAM
  - ScoreCAM
metrics:
  - road_combined
  - deletioncurveauc
  - insertioncurveauc
  - infidelity
  - averagedrop
  - coherency
  - complexity
  # - roc_auc
  # - mass_iou
upscale_methods:
  - SimpleUpsampling
  # - ERFUpsamplingFast
mixing_methods:
  # - IdentityMix
  # - MultiplierMix
  # - LogExpMix
  # - NthRootMultiplierMix
  - ExpMeanMix

# model_path: ./models/weights/ResNet18_Syntetic.pth
output_path: ./results_swin_imagenet.csv
device: cuda:0
num_samples: 1000
