model: swin
dataset: synthetic
attribution_methods:
  - GradCAMPlusPlus
  - LayerCAM
  - ScoreCAM
metrics:
  - road_combined
  - deletioncurveauc
  - insertioncurveauc
  - infidelity
  - averagedrop
  - coherency
  - complexity
  - roc_auc
  - mass_iou
upscale_methods:
  - SimpleUpsampling
  # - ERFUpsamplingFast

model_path: ./models/weights/swin_synthetic.pt
output_path: ./results_swin_synth.csv
device: cuda:0
