model: swin
dataset: synthetic_all
attribution_methods:
  - GradCAMPlusPlus
  - LayerCAM
  - ScoreCAM
  - RandomCAM
  # - HalfCAM
metrics:
  # - road_combined
  # - deletioncurveauc
  # - insertioncurveauc
  # - infidelity
  # - averagedrop
  # - coherency
  # - complexity
  # - roc_auc
  # - mass_iou
  # - bce
  # - l2masknorm
  - CosineSimilarity
upscale_methods:
  - SimpleUpsampling
  # - ERFUpsamplingFast
mixing_methods:
  - IdentityMix
  - MultiplierMix
  # - LogExpMix
  # - NthRootMultiplierMix
  # - ExpMeanMix

model_path: ./models/weights/Swin_Synthetic_All.pt
output_path: ./results_swin_synth_all.csv
device: cuda:1
# num_samples: 1
